name: pigeon_map
version: 0.1.001
author: tatumizer <tatumizer@gmail.com>
description: Implementation of Map for the case when keys are known in advance
homepage: https://github.com/tatumizer/dart-bench
environment:
  sdk: '>=0.5.0'
dependencies:
  unittest: <=1.0.0

#dependencies:
#  unittest: any