name: pigeon_map
version: 0.1.003
author: tatumizer <tatumizer@gmail.com>
description: Implementation of Map for the case when keys are known in advance
homepage: https://github.com/tatumizer/pigeon_map
environment:
  sdk: '>=0.5.0'
dev_dependencies:
  unittest: <=1.0.0

#dependencies:
#  unittest: any